### ISSUE TITLE
Needs sudo to serve on port lower than 1024

### ISSUE THREAD

**Issue by boblemarin** [leny/seve#1]
"seve -p 80" will crash.
"sudo seve -p 80" will run fine.

It could be nice to warn about it somewhere,
or just catch the error and show a nice message instead in the console.

**Comment by leny** [comment]
Hi, thanks for the report.

Will add it soon.

**Comment by boblemarin** [comment]
t'es vraiment un pro.

**Comment by leny** [comment]
Merci, chaton.

**Comment by leny** [comment]
Done & published as version `0.3.0`.
